export const CHANGE_TOPIC = "CHANGE_TOPIC";

export const GET_ANSWER = "GET_ANSWER";
export const GET_ANSWER_SUCCESS = "GET_ANSWER_SUCCESS";

export const GET_QUESTIONS = "GET_QUESTIONS";
export const GET_QUESTIONS_SUCCESS = "GET_QUESTIONS_SUCCESS";

export const GET_TOPICS = "GET_TOPICS";
export const GET_TOPICS_SUCCESS = "GET_TOPICS_SUCCESS";

export const INITIALIZE = "INITIALIZE";
